site_name: pycaphlowers
site_url: http://pycaphlowers.readthedocs.com
repo_url: https://github.com/phlowers/pycaphlowers
copyright: Copyright &copy; 2026 RTE France. Unless otherwise indicated, content is licensed under CC-BY-4.0.

theme:
  name: "material"
  logo: _static/logos/phlowers_64x64.ico
  favicon: _static/logos/phlowers_32x32.ico
  features:
    - toc.integrate
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  icon:
    repo: fontawesome/brands/github
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: home/home.md
  - Developer guide:
      - API Reference:
          - Example: docstring/example.md

plugins:
  - search
  - offline
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: False
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [src]
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          options:
            docstring_options:
              ignore_init_summary: true
            # docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            # show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            # summary: true

markdown_extensions:
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks
  # - tables
  - pymdownx.extra
  - pymdownx.highlight:
      pygments_lang_class: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phlowers
      name: phlowers on Github
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rte_france
      name: RTE France on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/myRTEtube
      name: RTE France on Youtube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rte_245681
      name: RTE France on LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/rte_france
      name: RTE France on Instagram
#   version:
#     provider: mike
